- README.md
Fixes a typo as well as some indentation problems in the documentation
> Fix typo and indentation

- lua/gluatest/expectations/positive.lua
Solves situations like this:
```
Expected function: 0x7f56cc5ec010 to error with 'Expected a string.', got 'addons/project/lua/my/code.lua:35: Expected a string.'
```
> Fix "expect.errWith()" expecting filename and line number prepended to the message

- lua/gluatest/runner/helpers.lua
This helps if GLuaTest is not installed as an addon or in a different path, for whatever reason that may be. :^)
> Do not require gluatest as an addon when inspecting the stack

- lua/gluatest/runner/runner.lua
This should fix the issue presented in #23
> Ignore expectations in late async tests

- lua/gluatest/expectations/negative.lua
- lua/gluatest/expectations/positive.lua
The negative expectations weren't even taking in any args, so I fixed that up.
Then I noticed that the error parsing itself didn't work if the error message had a colon in it, so I believe I fixed that too.
> Fix negative errWith, fix error parsing in both

- README.md
- lua/gluatest/stubs/stubMaker.lua
This PR adds a new method on stubs. It lets you tell a stub to return a sequence of values as it's called.
```lua
stub( net, "ReadString" ).returnsSequence( { "first", "second", "third", "fourth", "fifth", [50] = "fiftieth" }, "" )
```
Would effectively translate to:
```lua
print( net.ReadString() )
> first
print( net.ReadString() )
> second
print( net.ReadString() )
> third
print( net.ReadString() )
> fourth
print( net.ReadString() )
> fifth
print( net.ReadString() )
> ""
... 44 calls later
print( net.ReadString() )
> fiftieth
print( net.ReadString() )
> ""
```
I tested this _reasonably_ well, so I'm just gonna merge it and fix issues that pop up with it 🙃
> Add stub.returnsSequence

- lua/gluatest/runner/helpers.lua
- lua/gluatest/stubs/stubMaker.lua
Currently, if you do:
```lua
-- code
myProject.CallHook( name, ... )
hook.Run( name, ... )
end
-- test
func = function()
local runStub = stub( hook, "Run" )
myProject.CallHook( "test" )
expect( runStub ).to.haveBeenCalled()
end
```
This would fail, because the `stub` library is trying to stub `Run` on the _fake_ `hook` library that we set in the test environment.
The fix presented here would give the `hook` (and probably `timer`?) environment tables a metatable that would pass-through SET operations to the real `hook` (and `timer`) tables, letting stubs actually stub the real functions.
I didn't notice any side effects from doing this, but I'm going to play with it a bit more before merging.
e: One obvious issue here is that if you stub out any of the real hook methods, it'll fuck up …
> Fix tests that try to stub the hook table

- .github/workflows/run_tests.yml
- lua/gluatest/runner/logger.lua
ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update set-output usage

- README.md
- lua/gluatest/expectations/expect.lua
- lua/gluatest/expectations/negative.lua
- lua/gluatest/expectations/positive.lua
- lua/gluatest/init.lua
The goal here is to make some expectations "feel" better when writing them out.
e.g.
```lua
expect( func ).to.haveBeenCalled()
```
vs.
```lua
expect( func ).was.called()
```
> Add "was" expectation prefix

- lua/gluatest/runner/log_helpers.lua
- lua/gluatest/runner/logger.lua
- lua/gluatest/runner/runner.lua
Addresses #39 by adding a general summary at the end of the test run.
> Add summary and failure summary

- lua/gluatest/runner/logger.lua
- lua/gluatest/runner/runner.lua
Adds non colored logs at start and end of test to allow programs such as a gluatest CLI to filter the gluatest output without parsing colors
> add PlainLogEnd and PlainLogStart

- README.md
- lua/gluatest/runner/logger.lua
- lua/gluatest/runner/runner.lua
This feature easily allows cases to be skipped, or only ran conditionally. For example, if your behavior is intended (or expected) to be different across JIT versions, you could do:
```lua
return {
groupName = "isrunning action",
cases = {
{
name = "Is not valid on 32bit versions",
when = jit.version == "LuaJIT 2.0.4",
func = function()
expect( collectgarbage, "isrunning" ).to.errWith( [[bad argument #1 to '?' (invalid option 'isrunning')]] )
end
},
{
name = "Is valid on x86-64",
when = jit.version == "LuaJIT 2.1.0-beta3",
func = function()
expect( collectgarbage, "isrunning" ).to.succeed()
expect( collectgarbage( "isrunning" ) ).to.beA( "boolean" )
end
},
}
}
```
This also adds a new classification of output at the end; `SKIP`
> Add skip/when case keys

- lua/gluatest/runner/runner.lua
The group timeouts were a hacky feature. I probably added it as a band-aid fix to stuck test runs.
However, it also introduced unexpected and arguably undocumented functionality.
When a user reads that async test cases have a default timeout of 60 seconds, they assume that omitting `timeout =` from their test case would simply make that value default to 60.
Instead, there was a per-group timer that would continue to the next test group if it expired. This isn't technically the same behavior, and should be simplified.
With this change, a timer is created for every single case with no group timeout.
> Refactor group timeouts

- lua/gluatest/init.lua
- lua/gluatest/loader.lua
- lua/gluatest/runner/logger.lua
- lua/gluatest/runner/test_group_runner.lua
- lua/gluatest/types.lua
This solves #62
I tested it locally using https://github.com/CFC-Servers/gmod_tests & created a error in one of the files
If a test fails to be loaded it's now reported like this:
It could probably be further improved by using the OnLuaError hook, as pcall seemingly can't really catch include errors, but this already should do just fine.
> Try to handle include errors

- .github/workflows/run_tests_runnerimprovements.yml
- docker/Dockerfile
[+] You can now use `dev` & `prerelease`
[+] You can now specify a artifact to use.
[#] You now have `env.GLUA_REPO` to specify the GLuaTest repo to use, makes it easier for forks to change the workflow.
[#] Fixed a bug where git would fail as it never entered the `gluatest` directory.
[#] Fixed an issue with `git describe` where it would fail if the repo had no tags at all, instead it now falls back to `0.00`.
> Allow one to use dev & prerelease, Allow one to specify a artifact to use and some other minor changes

- .github/workflows/run_tests_runnerimprovements.yml
- docker/Dockerfile
- docker/entrypoint.sh
This will allow for some crash handling, but the main issue I found is that the core files are not generated in the base path, causing the debug.log's to end up empty.
> [!NOTE]
> Currently if the GLuaTest runner crashes it reboots every time and retries until it hits the timeout where it's then completes as succeded.
I would just do `echo "core" > /proc/sys/kernel/core_pattern` but docker complains that it's a read-only filesystem >:(
So I need to figure out how to set the core pattern somehow (if anyone knows how pls help xd).
> Try to handle crashes

- .github/workflows/run_tests.yml
- .github/workflows/self_tests.yml
- docker/Dockerfile
- docker/entrypoint.sh
- docker/testfixture/lua/includes/dev_server_test.lua
- lua/gluatest/runner/helpers.lua
- lua/tests/gluatest/init.lua
[+] Added `additional-setup` input to allow one to execute command/scripts on setup
[#] Fixed entrypoint using `serverfiles_override` instead of `garrysmod_override`
[#] Fixed tar complaining if no artifacts exist
[#] Fail the workflow if GLuaTest failed to exit clearly -> Should only happen if there was some error
[#] Fixed it failing on "Pull GLuaTest Runner" as it didn't enter the right directory
> Extent artifact argument & add "additional-setup" input & some fixes

- .github/workflows/run_tests.yml
If you want to give it a artifact that already contains everything, a repo checkout isn't needed.
> Allow one to skip the override directory / have no checkout

- README.md
- docker/testfixture/lua/includes/dev_server_test.lua
- lua/gluatest/init.lua
- lua/gluatest/loader.lua
- lua/gluatest/runner/helpers.lua
- lua/gluatest/runner/logger.lua
- lua/gluatest/runner/test_case_runner.lua
- lua/gluatest/runner/test_group_runner.lua
- lua/gluatest/types.lua
- Lower default case timeout to 5s
- Print error details when they happen, and also after the test run concludes
- Fix LuaLS type issues
- Added `GLuaTest_TestGroupLoaded`
- Fixed expectations in callbacks in async functions (I think?)
> Lower default timeout, print err details at the end, fix type errs

- docker/docker-compose.yml
The Docker workflow complains that this variable is no longer used during the startup sequence, so I'm just removing it per the warning message.
`time="2025-05-05T18:57:30Z" level=warning msg="/home/runner/work/ACF-3/ACF-3/gluatest/docker/docker-compose.yml: the attribute "version" is obsolete, it will be ignored, please remove it to avoid potential confusion"`
> Remove deprecated Docker variable

- docker/entrypoint.sh
- lua/gluatest/runner/helpers.lua
If you have a lot of workflows running in one go, these annotations can quickly stack up like this:
Since the workflow only succeeds when everything goes fine, it's pointless to have the ::notice:: add a annotation to the run.
> Don't use ::notice:: since it's pointless
